// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'app_widget.dart';

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/view/welcome',
        uri: Uri.parse('/view/welcome'),
        routeBuilder: b0Builder,
      ),
      RouteEntity(
        key: '/view/search',
        uri: Uri.parse('/view/search'),
        routeBuilder: b1Builder,
      ),
      RouteEntity(
        key: '/view/create',
        uri: Uri.parse('/view/create'),
        routeBuilder: b2Builder,
      ),
    ];

const routePaths = (
  path: '/',
  view: (
    path: '/view',
    welcome: '/view/welcome',
    search: '/view/search',
    create: '/view/create',
  ),
);
