// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'app_widget.dart';

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/view/welcome',
        uri: Uri.parse('/view/welcome'),
        routeBuilder: b0Builder,
      ),
    ];

const routePaths = (
  path: '/',
  view: (
    path: '/view',
    welcome: '/view/welcome',
  ),
);
